// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNSUWZzOmnbl9wq6oDe_P6KkdW3zBlVTE',
    appId: '1:1072529153607:android:900b134da3f8bc70d2db62',
    messagingSenderId: '1072529153607',
    projectId: 'yourspotv2',
    databaseURL: 'https://yourspotv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourspotv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASad6xN8exhSVZLlvEvjG5W5J9qdNJ4FM',
    appId: '1:1072529153607:ios:5abecbf83a84b52ad2db62',
    messagingSenderId: '1072529153607',
    projectId: 'yourspotv2',
    databaseURL: 'https://yourspotv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourspotv2.appspot.com',
    iosClientId: '1072529153607-ido03m8vrg11a6tabtpv9pl5njtshfeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourspotV2',
  );
}
